battles/urls.py
from django.urls import path
from . import views
app_name = 'battles'

urlpatterns = [
    path('',views.battles,name='index'),
    path('request',views.request_battle,name='request'),
    path('requests', views.battle_requests, name = 'requests'),
    path('waiting_refree',views.waiting_refree, name='waiting_refree'),
    path('not_started',views.not_yet_started, name="not_started"),

    path("filter/<int:filter_num>",views.filter_battle, name='filter'),

    path('rules/<int:battle_id>', views.rules,name= 'rules'),
    path('battle_room/<int:battle_id>',views.battle_room, name="battle_room"),
    path('textpads/get/<int:battle_id>',views.get_textpads, name="get_textpads"),
    path('textpads/send/<int:battle_id>',views.send_textpad, name="send_textpad"),
    path('textpads/evaluate/<int:battle_id>',views.evaluate_textpad, name='evaluate_textpad'),

    path('declare_winner/<int:battle_id>', views.declare_winner, name = "declare_winner"),

    path('refree/send_proposal/<int:battle_id>',views.refree_proposal,name="refree_proposal"),
    path('refree/validate/<int:proposal_id>',views.validate_refree, name='validate_refree'),
    path('referees',views.referees, name ='referees'),
    path('refrees/new_refree',views.new_refree, name ='new_refree'),
    path('referee/rate/<int:battle_id>',views.rate_referee, name = 'rate_referee'),

    path('accept/<int:request_id>',views.accept_battle, name = 'accept'),
    path('new/<int:acceptor_id>',views.init_battle, name="new_battle"),

    path('challenge/send/<int:target_id>',views.send_challenge, name='send_challenge'),
    path('challenge/answer/<int:challenge_id>',views.answer_challenge, name='accept_challenge'),


    

    

    
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.index,name='index'),
    path('<str:category>/posts',views.category, name='category'),
    path('posts/321<int:post_id>',views.blog_post, name='blog_post'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('home',views.home,name='home'),
    path('search/<str:scope>',views.search_all,name = "search"),
    path('feed',views.get_posts,name='feed'),
    path('post/new',views.create_post, name='create_post'),
    path('post/delete/<int:id>',views.delete_post,name='delete_post'),
    path('post/modify/<int:id>',views.modify_post,name = 'modify_post'),
    path('post/<int:id>',views.post, name = 'post'),
    path('comment/<int:id>',views.comment, name = 'comment_action'),
    path('posts/<int:id>',views.post_page, name = 'post_page'),
    path('post/favorite/<int:id>',views.favorite, name = "favorite"),
    

    
    path('post/react/<int:post_id>',views.react_post,name="react"),
    path('post/comment/new/<int:post_id>',views.create_comment, name="comment"),
    path('comment/react/<int:comment_id>',views.react_comment,name="react_comment"),
    
    path('notifications', views.notifications, name='notifications'),
    path('notifications/all',views.get_notifications, name='all_notifications'),
    path('battle points',views.battle_points, name="battle_points"),

    path('rankings', views.rankings, name = 'rankings'),

]

para/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('adminxyz/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('users/',include('users.urls',namespace='users')),
    path('chats/',include('chat.urls',namespace='chats')),
    path('characters/',include('characters.urls',namespace='characters')),
    path('battles/',include('battles.urls',namespace='battles')),
    path('events/',include('events.urls',namespace='events')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('moderator/', include('moderator.urls', namespace = 'moderator')),
    path('legal/', include('legal.urls', namespace = 'legal')),
    path('accounts/', include('allauth.urls')),
    path('',include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # path('info',views.validate_info,name='validate'),
    path('test_template',views.test_template,name='test_template'),
    path('signup',views.register,name='register'),
    path('signin',views.login,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('password/recover', views.password_recover, name = 'password_recover'),
    path('password/reset', views.password_reset, name = 'password_reset'),
    path('verify_username', views.verify_username, name="verify_username"),
    path('verify_email', views.verify_email, name="verify_email"),
    path('verify_password', views.verify_password, name="verify_password"),
    path('verify_passwords',views.verify_passwords, name= "verify_passwords"),

    path('families',views.families,name='families'), 
    path('families/rankings',views.family_rankings, name= 'family_rankings'),
    path('families/rankings/data',views.get_families_rankings, name = 'families_rankings_json'),


    path('profile',views.player_profile, name='profile'),

    # path('family',views.family,name="family"),
    path('family/new',views.new_family,name='new_family'),
    path('verify_family_name', views.verify_family_name, name="verify_family_name"),
       

    # path('battles',views.battles, name= 'battles'),
    path('posts/<str:name>',views.player_posts,name = 'player_posts'),
    path('battles/<str:name>',views.player_battles, name= 'player_battles'),
    path('requests',views.battle_requests, name='battle_requests'),
    path('requests/<str:name>',views.player_battle_requests, name='player_battle_requests'),
    path('statistics/<str:name>', views.stats, name = 'player_stats'),
    path('challenges/<str:name>', views.challenges, name = 'player_challenges'),

    path('send_request/<int:family_id>',views.send_request,name='send_request'),
    path('refuse_request/<int:notif_id>',views.refuse_request, name='refuse_request'),
    path('send_invite/<int:target_id>',views.send_invite,name="send_invite"),
    path('join_family/<int:notif_id>',views.join_family,name="join_family"),
    path('accept_request/<int:notif_id>',views.accept_request,name="accept_request"),
    path('family/65744<int:family_id>',views.family_page,name='family_page'),
    path('family/65744<int:family_id>/battles',views.family_battles,name='family_battles'),
    path('family/members/<int:family_id>', views.get_members, name = 'family_members'),
    path('family/promote/<int:player_id>',views.promote_member,name = 'promote_member'),
    path('family/demote/<int:player_id>',views.demote_member,name = 'demote_member'),
    path('family/remove/<int:player_id>',views.remove_member,name = 'remove_member'),
    

    path('notification/<int:id>/<str:type>',views.player_notif,name="notif"),
    path('players',views.get_players, name="players"),

    path('player/edit_info',views.edit_info, name = 'edit_info'),
    
   
    path('players/rankings', views.players_ranking, name = 'players_rankings'),    

    path('player/favorites',views.favorites, name = "favorites"),
    path('<str:name>',views.player,name='player'),

    
    
]

battles/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.models import User,auth
from django.urls import reverse
from django.http import HttpResponseRedirect,JsonResponse,Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from django.db.models import Q
from users.models import Player,Family,PlayerStat,PlayerNotification,notification_types,rankings,Badge,PlayerBadge
from users.users_utility import get_player
import core.models as core_models
import events.models as events_models
import events.views as events_views
import uuid
from datetime import datetime
from utility import get_characters,get_refree_questions,_parse_number,_time_since
import json
from django.views.decorators.csrf import csrf_exempt
import core.views as core_views
import users.views as users_views
import random

#manage progressions after a battle
#manage BP for starting a battle
#refree quizz

def update_battle_spectators(player:Player, battle:Battle):
    spectators = battle.spectators.all()
    
    if player in spectators:
       
       return
    elif battle.status != 'ongoing':
        
        return
    elif player == battle.initiator or player == battle.opponent:
        return
    else:
        
        battle.spectators.add(player)
        battle.save()  

def can_refree(player:Player,battle:Battle):
    #check if player can refree  the battle
    #can refree if:
    #   battle status is  waiting_refree
    #   battle has no refree
    #   player is not a fighter in the battle

    if battle.status == battle_status[0] and not battle.refree:  
        if battle.initiator != player  and battle.opponent != player:  
            return True    
        
    return False

def battle_result(player, battle):
    if battle.status == 'finished':
        if battle.winner == player:
            return "win"
        else:
            return "defeat"
    else:
        return "TBD"    

def _referee_proposals_data(proposals):
    data = [{
        "id": proposal.id,
        "player":{
            "id": proposal.player.id,
            "player": str(proposal.player),
            "username": proposal.player.user.username,
            "rank": proposal.player.rank,
            "profile_picture": proposal.player.profile_picture.url,
        },
        
        "ratings": (get_referee_rating(proposal.player)['timeliness']+get_referee_rating(proposal.player)['communication']+get_referee_rating(proposal.player)['fairness'])/3,
        "date_sent":  _time_since(proposal.date_sent),

    } for proposal in proposals ]
    return data

def _referee_proposals(battle:Battle, player:Player):
    if player == battle.initiator:
        return  _referee_proposals_data(RefreeingProposal.objects.filter(battle = battle))
    else:
        return None

def _battle_data(player,battle):
    data = {
            "feed_item":'battle',
            "id":battle.id,
            "status": battle.status,
            "isFighter":player == battle.opponent or player == battle.initiator,
            "initiator": {
                "id": battle.initiator.id,
                "player":str(battle.initiator),
                "username": battle.initiator.user.username,
                "profile_picture": battle.initiator.profile_picture.url,
                "rank":battle.initiator.rank,
                },
            "opponent": {
                "id": battle.opponent.id,
                "player":str(battle.opponent),
                "username": battle.opponent.user.username,
                "profile_picture": battle.opponent.profile_picture.url,
                "rank":battle.opponent.rank,
                },
            "refree": {
                "id": battle.refree.id,
                "player":str(battle.refree),
                "username": battle.refree.user.username,
                "profile_picture": battle.refree.profile_picture.url,
                "rank":battle.refree.rank,
                "rating": 2,
                } if battle.refree else None, 
            "winner": {
                "id":battle.winner.id,
                "player":str(battle.winner),
            } if battle.winner else None,
            "result": battle_result(player=player, battle=battle),       
            "i_character": battle.i_character,
            "o_character": battle.o_character,
            "type":battle.type,
            "can_refree": can_refree(player, battle),
            "spectators": _parse_number(len(battle.spectators.all()), True),
            "referee_proposals": _referee_proposals(battle,player),
            "date": core_views._time_since(battle.date_started),
        }
    return data

def _battles_data(player:Player,battles):
    
    data = [
        {   
            "feed_item":'battle',
            "id":battle.id,
            "status": battle.status,
            "isFighter":player == battle.opponent or player == battle.initiator,
            "initiator": {
                "id": battle.initiator.id,
                "player":str(battle.initiator),
                "username": battle.initiator.user.username,
                "profile_picture": battle.initiator.profile_picture.url,
                "rank":battle.initiator.rank,
                },
            "opponent": {
                "id": battle.opponent.id,
                "player":str(battle.opponent),
                "username": battle.opponent.user.username,
                "profile_picture": battle.opponent.profile_picture.url,
                "rank":battle.opponent.rank,
                },
            "refree": {
                "id": battle.refree.id,
                "player":str(battle.refree),
                "username": battle.refree.user.username,
                "profile_picture": battle.refree.profile_picture.url,
                "rank":battle.refree.rank,
                "rating": 2,
                } if battle.refree else None, 
            "winner": {
                "id":battle.winner.id,
                "player":str(battle.winner),
            } if battle.winner else None,
            "result": battle_result(player=player, battle=battle),       
            "i_character": battle.i_character,
            "o_character": battle.o_character,
            "type":battle.type,
            "can_refree": can_refree(player, battle),
            "spectators": _parse_number(len(battle.spectators.all()),True),
            "referee_proposals":_referee_proposals(battle,player),
            "date": core_views._time_since(battle.date_started),
        } for battle in battles
    ]

    return data

def _battle_requests_data(player:Player,battle_requests):
    data = [
        {
            "id":request.id,
            "type": request.type,
            "sender": {
                "player":str(request.sender),
                "username": request.sender.user.username,
                "profile_picture": request.sender.profile_picture.url,
                "rank":request.sender.rank,
                },
            "character": request.character,
            "date_sent": core_views._time_since(request.date_sent),
            

        } for request in battle_requests
    ]

    return data

def _isReferee(player:Player):
    isRefree = False

    player_badges = player.badges.all()
    referee_badge = Badge.objects.get(title = 'Referee')
    if referee_badge in player_badges:
        return True
    
    return False

@login_required
def battles(request):
    player = get_player(request.user)
    if not player:
        return redirect('/users/signin')
    characters = get_characters()
    sorted_characters = sorted(characters["playable_characters"], key = lambda item: item["name"])
    battles = Battle.objects.all().order_by('-date_started')
    requests = BattleRequest.objects.exclude(sender = player).order_by('-date_sent')
    requests_list = []

    #Show Number of battles initiated for each request  

    #remove requests where 3 battles had already being inititated from 
    for b_request in requests:
        r_battles = Battle.objects.filter(request = b_request)
        if len(r_battles)<=3:
            requests_list.append(b_request)

    battles_data = _battles_data(player, battles)

    context = {"requests":requests_list,
               "characters":sorted_characters,
               "player":player,
               "n_notifs":core_views.get_notifs(player),
               "battles":battles_data
               }
    return render(request,"battles/battles.html",context)

def create_request(sender:Player, character:str, type:str):
    

    new_request = BattleRequest.objects.create(sender=sender,
                                                        character = character,
                                                            type = type)
    
    #SET THE EXPIRY DATE and other details HERE

    if type == battle_types[0]:
        request_cost = f_request_cost
    elif type == battle_types[1]:
        request_cost = s_request_cost
    else:
        request_cost = 400

    sender.battle_points = sender.battle_points - request_cost
    new_request.save()
    sender.save()

    return new_request

def request_battle(request):
    if request.method == "POST":
        sender = Player.objects.get(user = request.user)
        character = request.POST['character']
        type = request.POST['type']
        
        #messages.success(request, "request created")
        if type == "stake": 
            if sender.battle_points < request_cost:
                messages.error(request,"Pas assez de Jetons de combat")    
                
            elif not sender.family:
                messages.error(request,"Tu dois étre dans une famille pour faire des combats STAKE")    
                 
            else:    
                new_request = BattleRequest.objects.create(sender=sender,
                                                        character = character,
                                                            type = type)

users/templates/users/user/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{{player}}</title>
    </head>
    <body>
        <a href="{%  url 'core:home' %}"><h1>Home</h1></a>
        {% block content %}
        {% endblock content %}
    </body>
</html>

users/templates/users/user/favorites.html
{% extends "core/base.html" %}

{% block content %}
<style>
    @layer utilities {
        .line-clamp-2 {
            display: -webkit-box;
            -webkit-line-clamp: 2;
            -webkit-box-orient: vertical;
            overflow: hidden;
        }
    }
</style>

<div class="max-w-3xl text-white mx-auto mt-28 px-4">
    <h2 class="text-xl  font-bold text-orange-500 mb-4">Saved Posts</h2>
    <div id="saved-posts-container pb-10" class="space-y-4">
        {% for post in posts %}
        <a href="{% url 'core:post_page' post.id %}" class="bg-gray-700 rounded-lg p-4 flex items-start space-x-4 transition-transform duration-200 hover:-translate-y-1 cursor-pointer">
            {% if post.image %}
            <img src="{{post.image.url}}" alt="Post image" class="w-24 h-24 object-cover rounded-md flex-shrink-0">
            {% endif %}
            <div class="flex-grow">
                <p class="line-clamp-2 mb-2">{{post.body}}</p>
                <p class="text-sm text-gray-400">
                    <span class="text-orange-500 font-semibold">{{post.author}}</span> • {{post.date_added|date:'M d, Y'}}
                </p>
            </div>
        </a>
        {% empty %}
        <div class="flex flex-col justify-center items-center py-5">
            <svg class="w-40 h-40 text-gray-300 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                <path stroke="currentColor" stroke-linejoin="round" stroke-width="1.7" d="M10 12v1h4v-1m4 7H6a1 1 0 0 1-1-1V9h14v9a1 1 0 0 1-1 1ZM4 5h16a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Z"/>
            </svg>
            <div>
                Your saved posts will be shown here
            </div>
            
              
         </div>
        {% endfor %}
    </div>
</div>

<div class="mb-4 md:hidden">
    <p class="opacity-0">Margin</p>
</div>


{% endblock content %}

users/templates/users/user/profile.html
{% extends "core/base.html" %}

{% block content %}


   

<style>
    .popup {
      display: none;
      position: fixed;
      top: 50%;
      left: 50%;
      width: 80%;
      transform: translate(-50%, -50%);
      background-color: white;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
      z-index: 1000;
    }

    .close-button {
      position: absolute;
      top: 10px;
      right: 10px;
      background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 15px;
        border-radius: 8px;
        cursor: pointer;
    }
</style>



<div id="comments" class="comments-area popup">
    <button id="close-btn" class="close-button"><i class="fa fa-times"></i></button>
  </div>

    <div class="container-profile">
        <div class="sidebar">
            <ul>
                <li><a href="#"><i class="fa fa-home"></i> Events</li></a>
                <li><a href="#"><i class="fa fa-cog"></i> tournaments</li></a>
                <li><a href="#"><i class="fa fa-user"></i> Tutorials</li></a>
                <li><a href="#"><i class="fa fa-cog"></i> Saved</li></a>
                <li><a href="#"><i class="fa fa-cogs"></i> Notifications</li></a>
                <li><button class="refree-btn">Request a Battle</button></li>
                <li><a href="#"><i class="fa fa-cogs"></i> Become a refree</a></li>
                <li><a href="{% url 'users:logout' %}"><i class="fa fa-sign-out-alt"></i> Logout</a></li>
            </ul>

        </div>
        {% block main_content %}
        <div class="main-content">
            <div class="profile-header">
                <div class="profile-info">
                    <img src="{{player.profile_picture.url}}" alt="Profile Picture">
                    <div class="user-details">
                        <div class="username">{{player}}</div>
                        {% if player.nickname %}
                        <div class="nickname">{{player.nickname}}</div>
                        {% else %}
                        <div class="nickname">@Add a nickname?</div>
                        {%endif%}
                    </div>
                </div>
                <div class="progress-section">
                    <div class="progress-circle">
                        <div class="progress-text">0%</div>
                    </div>
                    <div class="ranking">Rank: <span>{{player.rank}}</span></div>
                </div>
            </div>
            <div class="stats">
                <div class="stat-item"><strong>Wins:</strong>{{stats.wins}}</div>
                <div class="stat-item"><strong>Draws:</strong>{{stats.draws}}</div>
                <div class="stat-item"><strong>Losses:</strong>{{stats.losses}}</div>
            </div>
            <div class="navbar-profile">
                <a href="{% url 'users:profile' %}" class="profile-nav-link active" >Posts</a>
                <a class="profile-nav-link" href="{% url 'users:battles' %}">Your Battles</a>
                <a class="profile-nav-link" href="{% url 'users:battle_requests' %}">Requests</a>
                <a class="profile-nav-link" href="#">Statistiques</a>

            </div>
            <div class="content">
{% block center %}                
                <div class="posts">
                    <!-- Repeat this post-card for multiple posts -->
        {% for post in posts  %}
            <div class="post-card">
                <div class="post-header">
                    <img src="{{post.author.profile_picture.url}}" alt="Profile Picture">
                    <div class="post-info">
                        <div class="user-name">{{post.author}}</div>
                        <div class="post-time">2 hours ago</div>
                    </div>
                    <div class="post-options">
                        <i class="fa fa-ellipsis-h"></i>
                    </div>
                </div>
                <div class="post-content">
                    <div class="post-text">{{post.body}}</div>
                    {% if post.image %}
                    <img src="{{post.image.url}}" width="100%" height="100%" alt="Post Image" class="post-image">
                    {% endif %}
                </div>
                <div class="post-actions">
                        <button class="like-btn" data-post_id="{{post.id}}" data-link="{% url 'core:react' post.id %}">
                        {% if post.reacted %}
                        <i id="like-icon" class="fa fa-thumbs-up"></i>
                        {% else %}
                        <i id="like-icon" class="fa fa-thumbs-o-up"></i>
                        {% endif %}
                        <span id="post-likes-{{post.id}}">{{post.likes}}</span></button>
                    <button class="comment-btn" data-link="{% url 'core:post' post.id %}" data-post_id="{{post.id}}"><i class="fa fa-comment"></i></button>
                </div>
                <div class="comment-section">
                    <input id="input-comment-{{post.id}}"  type="text" placeholder="Write a comment...">
                    <button class="send-comment" data-post_id="{{post.id}}"  data-link="{% url 'core:comment' post.id %}"><i class="fa fa-paper-plane"></i></button>
                </div>
            </div>
        {% endfor %}
                </div>
                <div class="user-info">
                    <div class="info-box">
                        <div class="info-title">Bio</div>
                        {% if player.bio %}
                        <div class="info-content">{{player.bio}}</div>
                        {% else %}
                        <div class="info-content">No Bio, add one ?</div>
                        {%endif%}
                    </div>
                    <div class="info-box">
                        <div class="info-title">Battle Points</div>
                        <div class="info-content">{{player.battle_points}}</div>
                    </div>
                    <div class="info-box">
                        <div class="info-title">Gender</div>
                        <div class="info-content">{{player.gender}}</div>
                    </div>
                    <div class="info-box">
                        <div class="info-title">Favorite Character</div>
                        <div class="info-content">{{player.p_character}}</div>
                    </div>
                </div>
{% endblock center %}                
            </div>
        </div>
        {% endblock main_content %}
    </div>

<div>
    


    <!--
{% for request in requests %}
<h3>{{request.sender}} to fight with {{request.character}}</h3>

{% for accepted_request in  request.acceptors %}
<h3>{{accepted_request.player}} accepted this request and will use {{accepted_request.character}}- <button data-url="{% url 'battles:new_battle' accepted_request.id %}" id="btn-start-fight">Fight with {{accepted_request.player}}</button></h3> 
{% empty %}
<h3>Nobody accepted this request yet..</h3>
{% endfor %}

{% for refree_proposal in request.refree_proposals %}
<h3>{{refree_proposal}} - <button id="btn-validate-refree" data-url="{% url 'battles:validate_refree' refree_proposal.id %}">Validate refree</button></h3>
{% empty %}
<h3>no refree proposed this battle yet..</h3>
{% endfor %}

{% endfor %}
    -->

<script>
    $(()=>{
        $(".profile-nav-link").on("click",(e)=>{
            $(".profile-nav-link").removeClass("active")
            $(e.target).addClass("active")
        })
    })
</script>

<script>
$(()=>{
    $(".btn-start-fight").on("click",(e)=>{
        $.ajax({
            url: e.target.dataset.url,
            type:"POST",
            data:{csrfmiddlewaretoken:"{{csrf_token}}"},
            success: function(res){
                if(res.status == "success"){
                    console.log(res.message)
                }else{
                    console.log(res.message)
                }
            }
        })
    })


    $(".btn-validate-refree").on("click",(e)=>{
        $.ajax({
            url: e.target.dataset.url,
            type:"POST",
            data:{csrfmiddlewaretoken:"{{csrf_token}}"},
            success: function(res){
                if(res.status == "success"){
                    console.log(res.message)
                }else{
                    console.log(res.message)
                }
            }
        })
    })
})
</script>

<script>
     

    $(()=>{
        const popup = document.getElementById('comments');
    const closeButton = document.querySelector('#close-btn');
    $(".close-button").on('click', (e) => {
            
            popup.style.display = 'none';
            $("#comments").empty()
            });
    
        $(".like-btn").on("click",(e)=>{
           
            const post_id = String(e.target.dataset.post_id)
            $.ajax({
                url: e.target.dataset.link,
                type: "POST",
                data: { csrfmiddlewaretoken:"{{ csrf_token }}" },
                beforeSend: function(){
                    $(e.target).hide()
                    //show loader
                },
                success: function(res){
                    if(res.status == 'success'){
                        let likes_span = $(`#post-likes-${post_id}`)
                        let likes = parseInt(likes_span.text())
                        let like_icon = $(e.target).children().eq(0)
                        if(res.message == 'liked'){
                            like_icon.removeClass("fa fa-thumbs-o-up")
                            like_icon.addClass("fa fa-thumbs-up")

                            likes_span.text(likes+1)
                            
                        }else{
                            like_icon.removeClass("fa fa-thumbs-up")
                            like_icon.addClass("fa fa-thumbs-o-up")
                            likes_span.text(likes-1)
                            
                        }
                        

                    }

                },
                complete: function(){
                    $(e.target).show()
                    //remove loader
                }

            })
        })

        $(".comment-btn").on("click",(e)=>{
            popup.style.display = 'block';

            let url = e.target.dataset.link
            $.ajax({
                url:url,
                type:"GET",
                beforeSend: function(){
                    console.log("wait..")
                },
                success:function(res){
                    if(res.status == "success"){
                        console.log(res.post.comments)
                        $("#comments").append(
                        `<button id="close-btn" class="close-button"><i class="fa fa-times"></i></button>`
                        )
                        res.post.comments.forEach(comment => {
                            $("#comments").append(`
                            <div class="comment">
                                <b>${comment.author}</b>
                                <p>${comment.body}</p>
                            </div>    
                            `)
                            $(".close-button").on('click', (e) => {
                                popup.style.display = 'none';
                                $("#comments").empty()
                            });
    
                            
                        });
                            
                    }
                }
            })
        })

        $(".send-comment").on("click",(e)=>{
            console.log("clicked")
            let post_id = e.target.dataset.post_id

            $.ajax({
                url: e.target.dataset.link,
                type:"POST",
                data:{csrfmiddlewaretoken:"{{csrf_token}}","comment":$(`#input-comment-${post_id}`).val()},
                success: function(res){
                    console.log(res)
                }

            })
        })
        
    })
</script>


{%  endblock content %}