blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.index,name='index'),
    path('<str:category>/posts',views.category, name='category'),
    path('posts/321<int:post_id>',views.blog_post, name='blog_post'),
]

chat/urls.py
from django.urls import path
from . import views
app_name = 'chat'

urlpatterns = [
    path('',views.chats,name = "all"),
    path('search',views.search,name="search"),
    path('dm/<str:receiver_name>',views.private_chat,name="private_chat"),
    path('get_messages/<int:receiver_id>',views.get_messages,name="get_messages"),
    path('send_message/<int:receiver_id>',views.send_message,name="send_message"),
    #path('message/delete/<int:message_id>',),
    path('group/<str:family_name>',views.family_chat,name='family_chat'),
    path('group/get_messages/<str:family_name>',views.get_family_messages, name='get_family_messages'),
    path('messages/delete/private/<int:message_id>',views.delete_private_message, name = 'delete_private_message'),
    path('messages/delete/family/<int:message_id>',views.delete_family_message, name = 'delete_family_message'),

    #chat_box
    path('<str:chat_box_name>/',views.chat_box,name='chat_box'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('home',views.home,name='home'),
    path('search/<str:scope>',views.search_all,name = "search"),
    path('feed',views.get_posts,name='feed'),
    path('post/new',views.create_post, name='create_post'),
    path('post/delete/<int:id>',views.delete_post,name='delete_post'),
    path('post/modify/<int:id>',views.modify_post,name = 'modify_post'),
    path('post/<int:id>',views.post, name = 'post'),
    path('comment/<int:id>',views.comment, name = 'comment_action'),
    path('posts/<int:id>',views.post_page, name = 'post_page'),
    path('post/favorite/<int:id>',views.favorite, name = "favorite"),
    

    
    path('post/react/<int:post_id>',views.react_post,name="react"),
    path('post/comment/new/<int:post_id>',views.create_comment, name="comment"),
    path('comment/react/<int:comment_id>',views.react_comment,name="react_comment"),
    
    path('notifications', views.notifications, name='notifications'),
    path('notifications/all',views.get_notifications, name='all_notifications'),
    path('battle points',views.battle_points, name="battle_points"),

    path('rankings', views.rankings, name = 'rankings'),

]

para/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('adminxyz/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('users/',include('users.urls',namespace='users')),
    path('chats/',include('chat.urls',namespace='chats')),
    path('characters/',include('characters.urls',namespace='characters')),
    path('battles/',include('battles.urls',namespace='battles')),
    path('events/',include('events.urls',namespace='events')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('moderator/', include('moderator.urls', namespace = 'moderator')),
    path('legal/', include('legal.urls', namespace = 'legal')),
    path('accounts/', include('allauth.urls')),
    path('',include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # path('info',views.validate_info,name='validate'),
    path('test_template',views.test_template,name='test_template'),
    path('signup',views.register,name='register'),
    path('signin',views.login,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('password/recover', views.password_recover, name = 'password_recover'),
    path('password/reset', views.password_reset, name = 'password_reset'),
    path('verify_username', views.verify_username, name="verify_username"),
    path('verify_email', views.verify_email, name="verify_email"),
    path('verify_password', views.verify_password, name="verify_password"),
    path('verify_passwords',views.verify_passwords, name= "verify_passwords"),

    path('families',views.families,name='families'), 
    path('families/rankings',views.family_rankings, name= 'family_rankings'),
    path('families/rankings/data',views.get_families_rankings, name = 'families_rankings_json'),


    path('profile',views.player_profile, name='profile'),

    # path('family',views.family,name="family"),
    path('family/new',views.new_family,name='new_family'),
    path('verify_family_name', views.verify_family_name, name="verify_family_name"),
       

    # path('battles',views.battles, name= 'battles'),
    path('posts/<str:name>',views.player_posts,name = 'player_posts'),
    path('battles/<str:name>',views.player_battles, name= 'player_battles'),
    path('requests',views.battle_requests, name='battle_requests'),
    path('requests/<str:name>',views.player_battle_requests, name='player_battle_requests'),
    path('statistics/<str:name>', views.stats, name = 'player_stats'),
    path('challenges/<str:name>', views.challenges, name = 'player_challenges'),

    path('send_request/<int:family_id>',views.send_request,name='send_request'),
    path('refuse_request/<int:notif_id>',views.refuse_request, name='refuse_request'),
    path('send_invite/<int:target_id>',views.send_invite,name="send_invite"),
    path('join_family/<int:notif_id>',views.join_family,name="join_family"),
    path('accept_request/<int:notif_id>',views.accept_request,name="accept_request"),
    path('family/65744<int:family_id>',views.family_page,name='family_page'),
    path('family/65744<int:family_id>/battles',views.family_battles,name='family_battles'),
    path('family/members/<int:family_id>', views.get_members, name = 'family_members'),
    path('family/promote/<int:player_id>',views.promote_member,name = 'promote_member'),
    path('family/demote/<int:player_id>',views.demote_member,name = 'demote_member'),
    path('family/remove/<int:player_id>',views.remove_member,name = 'remove_member'),
    

    path('notification/<int:id>/<str:type>',views.player_notif,name="notif"),
    path('players',views.get_players, name="players"),

    path('player/edit_info',views.edit_info, name = 'edit_info'),
    
   
    path('players/rankings', views.players_ranking, name = 'players_rankings'),    

    path('player/favorites',views.favorites, name = "favorites"),
    path('<str:name>',views.player,name='player'),

    
    
]

chat/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.models import User,auth
from django.urls import reverse
from django.http import HttpResponseRedirect,JsonResponse,Http404
from django.contrib.auth import logout,login,authenticate
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from django.db.models import Q
from users.models import Player,Family
from users.users_utility import get_player
import core.views as core_views
import uuid
from datetime import datetime
import json
from django.views.decorators.csrf import csrf_exempt
from utility import decrypt_message,_date_time,_time_since,_parse_number,_time_since_last_seen
from cryptography.fernet import Fernet




def check_family_membership(player:Player,family:Family):
    return player.family == family

def get_last_message(chat,chat_type='private'):
    if chat_type == "private":
        messages = Message.objects.filter(chat = chat)
        
    last_message = messages.last()
    if last_message:
        return {
            "sender":last_message.sender.user.username,
            "receiver":last_message.receiver.user.username,
            "content":decrypt_message(last_message.content),
            'image': last_message.image.url if last_message.image else None, 
            'date_sent': _date_time(last_message.date_sent)
            }
    else:
        return ""
    

def get_player_last_seen(player:Player):
    last_seen = player.last_seen
    return _time_since_last_seen(last_seen)


def _get_family_unreads(player:Player):
    family = player.family
    if family:
        family_messages = FamilyMessage.objects.filter(family = family)
        count = [1 for msg in family_messages if player not in msg.readers.all()]
        return sum(count)
    
    else:
        return 0    


@login_required
def chats(request):
    current_player = get_player(request.user)
    if not current_player:
        return redirect('/users/signin')
    
    message_list=[]
    receivers = []
    
    chats = Chat.objects.filter(
        Q(initiator = current_player) | Q(recipient = current_player)
    ).order_by("-last_message_time_sent")
    
    #delete chats with no messages
    for chat in chats:
        chat_messages = Message.objects.filter(chat = chat)
        if not chat_messages.exists():
            chat.delete()

    chats_data = [
        {
            "chat": chat,
            "last_message": get_last_message(chat,"private"),
            'unreads': {
                'number':_parse_number(chat.unreads(current_player)),
                'label':'unread' if _parse_number(chat.unreads(current_player)) != '' else ''
            }

        }
        for chat in chats
    ]

    family_last_message = FamilyMessage.objects.filter(family = current_player.family).order_by('-date_sent').first()
        
    if family_last_message:
        content =  decrypt_message(family_last_message.content)[:7]+'...'
        if family_last_message.image:
            content = f'sent an image'
        fl_message_data = {
            "sender":family_last_message.sender.user.username,
            'content': content,
            'image': family_last_message.image.url if family_last_message.image else None, 
            'date_sent': _date_time(family_last_message.date_sent),
            'unreads': {
               'number': _parse_number(_get_family_unreads(current_player)),
               'label': 'unread' if _parse_number(_get_family_unreads(current_player)) != '' else ''
            }
            
        }
    else:
        fl_message_data = ''    

    context = {"chats":chats_data,
               "player":current_player,
               "family_last_message":fl_message_data,
               "n_notifs": core_views.get_notifs(current_player),
               }
    return render(request,"chat/chats.html",context)

def getchats(player):
    chats = Chat.objects.filter(
        Q(initiator = player) | Q(recipient = player)
    ).order_by("-last_message_time_sent")

    return chats

def mark_as_read(message:Message):
    message.read = True
    message.save()

def get_messages(request,receiver_id):    
    #receiver_user = User.objects.get(username = receiver_name)
    receiver = Player.objects.get(id=receiver_id)
    sender = Player.objects.get(user=request.user)
    #messages = Message.objects.filter(Q(sender = sender or receiver) &
    #                                   Q(receiver = receiver or sender))
    messages = Message.objects.filter(
        Q(sender = sender) |  Q(sender=receiver), 
        Q(receiver = receiver) | Q(receiver = sender)).order_by("date_sent")
    
    for msg in messages:
        if msg.receiver == Player.objects.get(user = request.user):
            msg.mark_as_read()
            #mark_as_read(msg)

    messages_data = [{
        "id":message.id,
        "sender":{
            'username':message.sender.user.username,
            'profile_picture': message.sender.profile_picture.url
            },
        "receiver":{
            'username':message.receiver.user.username,
            'profile_picture': message.sender.profile_picture.url,
            },
        "content":decrypt_message(message.content),
        'image': message.image.url if message.image else None, 
        'date_sent': _date_time(message.date_sent),
        'read': message.read,
        
        }
        for message in messages]
    return JsonResponse({"message":"success","messages":messages_data})

def mark_as_reader_family(player,family):
    messages = FamilyMessage.objects.filter(family = family)


def get_family_messages(request, family_name):
    family = Family.objects.get(name = family_name)
    sender = Player.objects.get(user=request.user)

    messages = FamilyMessage.objects.filter(
        family = family
    ).order_by('date_sent')
    #Mark All family messages as read
    for msg in FamilyMessage.objects.filter(family = family):
        if sender not in msg.readers.all():
            msg.readers.add(sender)

    messages_data = [
        {   "id":message.id,          
            "sender":{
                        'username':message.sender.user.username,
                        'profile_picture': message.sender.profile_picture.url
                     },
                      "family":message.family.name,
                      "content":decrypt_message(message.content),
                      'image': message.image.url if message.image else None, 
                        'date_sent': _date_time(message.date_sent),
                        
                      
                       }for message in messages
    ]
    return JsonResponse({"message":"success","messages":messages_data})

    

@login_required
def private_chat(request,receiver_name):
    
    player = get_player(request.user)
    if not player:
        return redirect('/users/signin')
    
    chats = getchats(player)
    try:
        receiver_user = User.objects.get(username = receiver_name)
        receiver = Player.objects.get(user=receiver_user)
        sender = Player.objects.get(user=request.user)
    except:
        return JsonResponse({"status":"error"}) 
       
    sent_messages = Message.objects.filter(sender = sender,receiver=receiver)
    sent_by_user = [x for x in sent_messages if x.sender==request.user]
    sent_by_receiver = [x for x in sent_messages if x.sender != request.user]

    chats_data = [
        {
            "chat": chat,
            "last_message": get_last_message(chat)

        }
        for chat in chats
    ]
    family_last_message = FamilyMessage.objects.filter(family = player.family).order_by('-date_sent').first()
    if family_last_message:
        content =  decrypt_message(family_last_message.content)[:7]+'...'
        if family_last_message.image:
            content = f'sent an image'
        fl_message_data = {
            "sender":family_last_message.sender.user.username,
            'content': content,
            'image': family_last_message.image.url if family_last_message.image else None, 
            'date_sent': _date_time(family_last_message.date_sent)
        }
    else:
        fl_message_data = ''    
        

    context = {"receiver":receiver,
               'last_seen': get_player_last_seen(receiver),
               "sent_messages":sent_messages,               
                "sent":sent_by_user,
                "received":sent_by_receiver,
                "room":"room1", 
                "player":player, 
                "chats":chats_data,
                "family_last_message":fl_message_data}
    return render(request,"chat/private_chat.html",context)
        
@csrf_exempt       
def delete_private_message(request, message_id):
    if request.method == "DELETE":
        player = get_object_or_404(Player, user=request.user)
        respond = ''
        
        message = get_object_or_404(Message, id = message_id)
        if player != message.sender:
            respond = "Can't delete a message you did not sent"
        else:
            message.delete()
            return JsonResponse({'status':'success', 'message':'message deleted'})
       
    return JsonResponse({'status':'failed', 'respond':respond})        

@csrf_exempt       
def delete_family_message(request, message_id):
    if request.method == "DELETE":
        player = get_object_or_404(Player, user=request.user)
        respond = ''
        
        message = get_object_or_404(FamilyMessage, id = message_id)
        if player != message.sender and player.user != message.family.god_father:
            respond = "Can't delete a message you did not sent"
        elif player.family != message.family:
            respond = "Message was sent in a family you do not belong to"
        else:    
            message.delete()
            return JsonResponse({'status':'success', 'message':'message deleted'})
    return JsonResponse({'status':'failed', 'respond':respond})        

chat/templates/chat/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Chat</title>
        <style>
            ul{
                list-style: none;

            }
            a{
                text-decoration: none;
            }
        </style>

        <link rel="stylesheet" href="{% static 'css/chats.css' %}" />
        <link rel="stylesheet" href="{% static 'css/private_chat.css' %}" />
        <link rel="stylesheet" href="{% static 'css/group_chat.css' %}" />

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
    <body>
        <a href="{% url 'users:logout' %}">Logout</a>
        <a href="{% url 'core:home' %}">Home</a>
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">Message</div>
        {% block content %}
        {% endblock content %}

        <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </body>
</html>

chat/templates/chat/chatbox.html
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        <style>
            .toast {
                max-width: 350px;
                padding: 12px 16px;
                border-radius: 4px;
                margin-bottom: 10px;
                margin: auto;
                box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
                display: flex;
                align-items: center;
                justify-content: space-between;
                animation: fadeInDown 0.5s forwards;
                /* animation-duration: 0.5s;
                animation-fill-mode: forwards;  */
            }
        
            .toast-success {
                background-color: #10B981;
                color: #ffffff;
            }
        
            .toast-error {
                background-color: #EF4444;
                color: #ffffff;
            }
        
            .toast-warning {
                background-color: #F59E0B;
                color: #ffffff;
            }
        
            .toast-info {
                background-color: #3B82F6;
                color: #ffffff;
            }
        
            .toast-close {
                background: none;
                border: none;
                color: #ffffff;
                cursor: pointer;
                font-size: 16px;
                margin-left: 10px;
            }
        
            @keyframes slideIn {
                from {
                    transform: translateX(100%);
                    opacity: 0;
                }
                to {
                    transform: translateX(0);
                    opacity: 1;
                }
            }
        
            @keyframes fadeOut {
                from {
                    opacity: 1;
                }
                to {
                    opacity: 0;
                }
            }
        </style>
        
</head>

<body>
    <div id="top-toastContainer" class="fixed top-4 right-4 z-50"></div>
    
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-3">
                <form>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1" class="h4 pt-5">Chatbox</label>
                        <textarea class="form-control" id="chat-text" readonly rows="10"></textarea><br>
                    </div>
                    <div class="form-group">
                        <input class="form-control" placeholder="Enter text here" id="input" type="text"></br>
                    </div>
                    <input class="btn btn-primary btn-lg btn-block" id="submit" type="button" value="Send">
                </form>
            </div>
        </div>
    </div>
    {% comment %} Get data for username and chatbox name{% endcomment %}
    {{ request.user.username|json_script:"user_username" }}
    {{ chat_box_name|json_script:"room-name" }}



    <!-- toast management -->
<script>
    
        const toastContainer = document.getElementById('top-toastContainer');
    
    function showToast(message, type = 'info', duration = 3000) {
        
        const toast = document.createElement('div');
        toast.className = `toast toast-${type}`;
        
        const messageSpan = document.createElement('span');
        messageSpan.textContent = message;
        
        const closeButton = document.createElement('button');
        closeButton.className = 'toast-close';
        closeButton.innerHTML = '&times;';
        closeButton.onclick = () => removeToast(toast);
        // toast.classList.add('animate__animated')
        // toast.classList.add('animate__fadeInDown')
        toast.appendChild(messageSpan);
        toast.appendChild(closeButton);
        
        toastContainer.appendChild(toast);
        console.log(messageSpan)
        console.log(toastContainer)
        // toast.style.animation = 'fadeOut 0.3s ease-out forwards';
        setTimeout(() => {
            toast.style.animation = 'fadeOutUp 0.3s ease-out forwards';
            setTimeout(() => removeToast(toast), 300);
        }, 3000);
    }
    
    function removeToast(toast) {
        toastContainer.removeChild(toast);
    }
    
    // Example usage:
    showToast('Battle started!', 'success');
    //showToast('Error loading battle data', 'error');
     //showToast('Your turn in 30 seconds', 'warning');
    // showToast('New message received', 'info');
    
    
    </script>




    <script>

//example socket 2
/*
        const chatSocket = new WebSocket(
            'ws://'+ window.location.host + '/ws/chat/'
        );

        chatSocket.onmessage = function(e){
            const data = JSON.parse(e.data)
            const message = data['message'];
            //Handle incoming msgs
        }

        chatSocket.onclose = function(e){
            console.error("this Chat socket closed unexpectedly");
        }

        function sendMessage(message){
            chatSocket.send(JSON.stringify({
                'message':message
            }))
        }

*/



  
  //example socket 1
  /*  const chatSocket = new WebSocket(
            'ws://' + 
            window.location.host + 
            '/ws/chat/'
        );
*/
       console.log(` window: ${window.location.host} \n `)
       const boxName = JSON.parse(document.getElementById('room-name').textContent)
       console.log(` box-name: ${document.getElementById('room-name').textContent} \n `)
       
       
       const chatSocket = new WebSocket(
            'ws://' + 
            window.location.host + 
            '/ws/chat/' + 
            boxName + 
            '/'
        );
        

        const user_username = JSON.parse(document.getElementById('user_username').textContent)
        document.querySelector("#submit").onclick = function (e){
            const messageInputDom = document.querySelector("#input");
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'username': user_username,
            }));
            console.log("sent")
            messageInputDom.value = '';

        };
        //const boxName = JSON.parse(document.getElementById('room-name').textContent)
        
        

        chatSocket.onmessage = function(e){
            const data = JSON.parse(e.data);
            document.querySelector('#chat-text').value += (data.message + ' sent by ' + data.username + '\n')  //adding message to text box
        }



    </script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous">
    </script>
</body>

</html>

chat/templates/chat/group_chat.html
{% block content %}
<h1>Group Chat</h1>
{% endblock content %}

chat/templates/chat/new_chat.html
{% extends "chat/base.html" %}
{% block content %}


<ul>
    {% for player in searched_players %}
    <li>{{player}} - <a href="#">Chat</a></li>
    {% empty %}
    <h5>No player Found</h5>
    {% endfor %}
</ul>

{% endblock content %}

chat/templates/chat/search.html
{% extends "chat/base.html" %}
{% block content %}


<ul>
    {% for player in searched_players %}
    <li>{{player}} - <a href="{% url 'chat:private_chat' player.user.username %}">Chat</a></li>
    {% empty %}
    <h5>No player Found</h5>
    {% endfor %}
</ul>

{% endblock content %}

chat/templates/chat/testbase.html
{% extends "core/base.html" %}


{%block inbox%}
{%endblock inbox%}