battles/urls.py
from django.urls import path
from . import views
app_name = 'battles'

urlpatterns = [
    path('',views.battles,name='index'),
    path('request',views.request_battle,name='request'),
    path('requests', views.battle_requests, name = 'requests'),
    path('waiting_refree',views.waiting_refree, name='waiting_refree'),
    path('not_started',views.not_yet_started, name="not_started"),

    path("filter/<int:filter_num>",views.filter_battle, name='filter'),

    path('rules/<int:battle_id>', views.rules,name= 'rules'),
    path('battle_room/<int:battle_id>',views.battle_room, name="battle_room"),
    path('textpads/get/<int:battle_id>',views.get_textpads, name="get_textpads"),
    path('textpads/send/<int:battle_id>',views.send_textpad, name="send_textpad"),
    path('textpads/evaluate/<int:battle_id>',views.evaluate_textpad, name='evaluate_textpad'),

    path('declare_winner/<int:battle_id>', views.declare_winner, name = "declare_winner"),

    path('refree/send_proposal/<int:battle_id>',views.refree_proposal,name="refree_proposal"),
    path('refree/validate/<int:proposal_id>',views.validate_refree, name='validate_refree'),
    path('referees',views.referees, name ='referees'),
    path('refrees/new_refree',views.new_refree, name ='new_refree'),
    path('referee/rate/<int:battle_id>',views.rate_referee, name = 'rate_referee'),

    path('accept/<int:request_id>',views.accept_battle, name = 'accept'),
    path('new/<int:acceptor_id>',views.init_battle, name="new_battle"),

    path('challenge/send/<int:target_id>',views.send_challenge, name='send_challenge'),
    path('challenge/answer/<int:challenge_id>',views.answer_challenge, name='accept_challenge'),


    

    

    
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.index,name='index'),
    path('<str:category>/posts',views.category, name='category'),
    path('posts/321<int:post_id>',views.blog_post, name='blog_post'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('home',views.home,name='home'),
    path('search/<str:scope>',views.search_all,name = "search"),
    path('feed',views.get_posts,name='feed'),
    path('post/new',views.create_post, name='create_post'),
    path('post/delete/<int:id>',views.delete_post,name='delete_post'),
    path('post/modify/<int:id>',views.modify_post,name = 'modify_post'),
    path('post/<int:id>',views.post, name = 'post'),
    path('comment/<int:id>',views.comment, name = 'comment_action'),
    path('posts/<int:id>',views.post_page, name = 'post_page'),
    path('post/favorite/<int:id>',views.favorite, name = "favorite"),
    

    
    path('post/react/<int:post_id>',views.react_post,name="react"),
    path('post/comment/new/<int:post_id>',views.create_comment, name="comment"),
    path('comment/react/<int:comment_id>',views.react_comment,name="react_comment"),
    
    path('notifications', views.notifications, name='notifications'),
    path('notifications/all',views.get_notifications, name='all_notifications'),
    path('battle points',views.battle_points, name="battle_points"),

    path('rankings', views.rankings, name = 'rankings'),

]

para/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('adminxyz/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('users/',include('users.urls',namespace='users')),
    path('chats/',include('chat.urls',namespace='chats')),
    path('characters/',include('characters.urls',namespace='characters')),
    path('battles/',include('battles.urls',namespace='battles')),
    path('events/',include('events.urls',namespace='events')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('moderator/', include('moderator.urls', namespace = 'moderator')),
    path('legal/', include('legal.urls', namespace = 'legal')),
    path('accounts/', include('allauth.urls')),
    path('',include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # path('info',views.validate_info,name='validate'),
    path('test_template',views.test_template,name='test_template'),
    path('signup',views.register,name='register'),
    path('signin',views.login,name='login'),
    path('logout',views.logout_view,name='logout'),
    path('password/recover', views.password_recover, name = 'password_recover'),
    path('password/reset', views.password_reset, name = 'password_reset'),
    path('verify_username', views.verify_username, name="verify_username"),
    path('verify_email', views.verify_email, name="verify_email"),
    path('verify_password', views.verify_password, name="verify_password"),
    path('verify_passwords',views.verify_passwords, name= "verify_passwords"),

    path('families',views.families,name='families'), 
    path('families/rankings',views.family_rankings, name= 'family_rankings'),
    path('families/rankings/data',views.get_families_rankings, name = 'families_rankings_json'),


    path('profile',views.player_profile, name='profile'),

    # path('family',views.family,name="family"),
    path('family/new',views.new_family,name='new_family'),
    path('verify_family_name', views.verify_family_name, name="verify_family_name"),
       

    # path('battles',views.battles, name= 'battles'),
    path('posts/<str:name>',views.player_posts,name = 'player_posts'),
    path('battles/<str:name>',views.player_battles, name= 'player_battles'),
    path('requests',views.battle_requests, name='battle_requests'),
    path('requests/<str:name>',views.player_battle_requests, name='player_battle_requests'),
    path('statistics/<str:name>', views.stats, name = 'player_stats'),
    path('challenges/<str:name>', views.challenges, name = 'player_challenges'),

    path('send_request/<int:family_id>',views.send_request,name='send_request'),
    path('refuse_request/<int:notif_id>',views.refuse_request, name='refuse_request'),
    path('send_invite/<int:target_id>',views.send_invite,name="send_invite"),
    path('join_family/<int:notif_id>',views.join_family,name="join_family"),
    path('accept_request/<int:notif_id>',views.accept_request,name="accept_request"),
    path('family/65744<int:family_id>',views.family_page,name='family_page'),
    path('family/65744<int:family_id>/battles',views.family_battles,name='family_battles'),
    path('family/members/<int:family_id>', views.get_members, name = 'family_members'),
    path('family/promote/<int:player_id>',views.promote_member,name = 'promote_member'),
    path('family/demote/<int:player_id>',views.demote_member,name = 'demote_member'),
    path('family/remove/<int:player_id>',views.remove_member,name = 'remove_member'),
    

    path('notification/<int:id>/<str:type>',views.player_notif,name="notif"),
    path('players',views.get_players, name="players"),

    path('player/edit_info',views.edit_info, name = 'edit_info'),
    
   
    path('players/rankings', views.players_ranking, name = 'players_rankings'),    

    path('player/favorites',views.favorites, name = "favorites"),
    path('<str:name>',views.player,name='player'),

    
    
]

battles/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.models import User,auth
from django.urls import reverse
from django.http import HttpResponseRedirect,JsonResponse,Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import *
from django.db.models import Q
from users.models import Player,Family,PlayerStat,PlayerNotification,notification_types,rankings,Badge,PlayerBadge
from users.users_utility import get_player
import core.models as core_models
import events.models as events_models
import events.views as events_views
import uuid
from datetime import datetime
from utility import get_characters,get_refree_questions,_parse_number,_time_since
import json
from django.views.decorators.csrf import csrf_exempt
import core.views as core_views
import users.views as users_views
import random

#manage progressions after a battle
#manage BP for starting a battle
#refree quizz

def update_battle_spectators(player:Player, battle:Battle):
    spectators = battle.spectators.all()
    
    if player in spectators:
       
       return
    elif battle.status != 'ongoing':
        
        return
    elif player == battle.initiator or player == battle.opponent:
        return
    else:
        
        battle.spectators.add(player)
        battle.save()  

def can_refree(player:Player,battle:Battle):
    #check if player can refree  the battle
    #can refree if:
    #   battle status is  waiting_refree
    #   battle has no refree
    #   player is not a fighter in the battle

    if battle.status == battle_status[0] and not battle.refree:  
        if battle.initiator != player  and battle.opponent != player:  
            return True    
        
    return False

def battle_result(player, battle):
    if battle.status == 'finished':
        if battle.winner == player:
            return "win"
        else:
            return "defeat"
    else:
        return "TBD"    

def _referee_proposals_data(proposals):
    data = [{
        "id": proposal.id,
        "player":{
            "id": proposal.player.id,
            "player": str(proposal.player),
            "username": proposal.player.user.username,
            "rank": proposal.player.rank,
            "profile_picture": proposal.player.profile_picture.url,
        },
        
        "ratings": (get_referee_rating(proposal.player)['timeliness']+get_referee_rating(proposal.player)['communication']+get_referee_rating(proposal.player)['fairness'])/3,
        "date_sent":  _time_since(proposal.date_sent),

    } for proposal in proposals ]
    return data

def _referee_proposals(battle:Battle, player:Player):
    if player == battle.initiator:
        return  _referee_proposals_data(RefreeingProposal.objects.filter(battle = battle))
    else:
        return None

def _battle_data(player,battle):
    data = {
            "feed_item":'battle',
            "id":battle.id,
            "status": battle.status,
            "isFighter":player == battle.opponent or player == battle.initiator,
            "initiator": {
                "id": battle.initiator.id,
                "player":str(battle.initiator),
                "username": battle.initiator.user.username,
                "profile_picture": battle.initiator.profile_picture.url,
                "rank":battle.initiator.rank,
                },
            "opponent": {
                "id": battle.opponent.id,
                "player":str(battle.opponent),
                "username": battle.opponent.user.username,
                "profile_picture": battle.opponent.profile_picture.url,
                "rank":battle.opponent.rank,
                },
            "refree": {
                "id": battle.refree.id,
                "player":str(battle.refree),
                "username": battle.refree.user.username,
                "profile_picture": battle.refree.profile_picture.url,
                "rank":battle.refree.rank,
                "rating": 2,
                } if battle.refree else None, 
            "winner": {
                "id":battle.winner.id,
                "player":str(battle.winner),
            } if battle.winner else None,
            "result": battle_result(player=player, battle=battle),       
            "i_character": battle.i_character,
            "o_character": battle.o_character,
            "type":battle.type,
            "can_refree": can_refree(player, battle),
            "spectators": _parse_number(len(battle.spectators.all()), True),
            "referee_proposals": _referee_proposals(battle,player),
            "date": core_views._time_since(battle.date_started),
        }
    return data

def _battles_data(player:Player,battles):
    
    data = [
        {   
            "feed_item":'battle',
            "id":battle.id,
            "status": battle.status,
            "isFighter":player == battle.opponent or player == battle.initiator,
            "initiator": {
                "id": battle.initiator.id,
                "player":str(battle.initiator),
                "username": battle.initiator.user.username,
                "profile_picture": battle.initiator.profile_picture.url,
                "rank":battle.initiator.rank,
                },
            "opponent": {
                "id": battle.opponent.id,
                "player":str(battle.opponent),
                "username": battle.opponent.user.username,
                "profile_picture": battle.opponent.profile_picture.url,
                "rank":battle.opponent.rank,
                },
            "refree": {
                "id": battle.refree.id,
                "player":str(battle.refree),
                "username": battle.refree.user.username,
                "profile_picture": battle.refree.profile_picture.url,
                "rank":battle.refree.rank,
                "rating": 2,
                } if battle.refree else None, 
            "winner": {
                "id":battle.winner.id,
                "player":str(battle.winner),
            } if battle.winner else None,
            "result": battle_result(player=player, battle=battle),       
            "i_character": battle.i_character,
            "o_character": battle.o_character,
            "type":battle.type,
            "can_refree": can_refree(player, battle),
            "spectators": _parse_number(len(battle.spectators.all()),True),
            "referee_proposals":_referee_proposals(battle,player),
            "date": core_views._time_since(battle.date_started),
        } for battle in battles
    ]

    return data

def _battle_requests_data(player:Player,battle_requests):
    data = [
        {
            "id":request.id,
            "type": request.type,
            "sender": {
                "player":str(request.sender),
                "username": request.sender.user.username,
                "profile_picture": request.sender.profile_picture.url,
                "rank":request.sender.rank,
                },
            "character": request.character,
            "date_sent": core_views._time_since(request.date_sent),
            

        } for request in battle_requests
    ]

    return data

def _isReferee(player:Player):
    isRefree = False

    player_badges = player.badges.all()
    referee_badge = Badge.objects.get(title = 'Referee')
    if referee_badge in player_badges:
        return True
    
    return False

@login_required
def battles(request):
    player = get_player(request.user)
    if not player:
        return redirect('/users/signin')
    characters = get_characters()
    sorted_characters = sorted(characters["playable_characters"], key = lambda item: item["name"])
    battles = Battle.objects.all().order_by('-date_started')
    requests = BattleRequest.objects.exclude(sender = player).order_by('-date_sent')
    requests_list = []

    #Show Number of battles initiated for each request  

    #remove requests where 3 battles had already being inititated from 
    for b_request in requests:
        r_battles = Battle.objects.filter(request = b_request)
        if len(r_battles)<=3:
            requests_list.append(b_request)

    battles_data = _battles_data(player, battles)

    context = {"requests":requests_list,
               "characters":sorted_characters,
               "player":player,
               "n_notifs":core_views.get_notifs(player),
               "battles":battles_data
               }
    return render(request,"battles/battles.html",context)

def create_request(sender:Player, character:str, type:str):
    

    new_request = BattleRequest.objects.create(sender=sender,
                                                        character = character,
                                                            type = type)
    
    #SET THE EXPIRY DATE and other details HERE

    if type == battle_types[0]:
        request_cost = f_request_cost
    elif type == battle_types[1]:
        request_cost = s_request_cost
    else:
        request_cost = 400

    sender.battle_points = sender.battle_points - request_cost
    new_request.save()
    sender.save()

    return new_request

def request_battle(request):
    if request.method == "POST":
        sender = Player.objects.get(user = request.user)
        character = request.POST['character']
        type = request.POST['type']
        
        #messages.success(request, "request created")
        if type == "stake": 
            if sender.battle_points < request_cost:
                messages.error(request,"Pas assez de Jetons de combat")    
                
            elif not sender.family:
                messages.error(request,"Tu dois étre dans une famille pour faire des combats STAKE")    
                 
            else:    
                new_request = BattleRequest.objects.create(sender=sender,
                                                        character = character,
                                                            type = type)

users/templates/users/family/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Manage Family</title>
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    </head>
    <body>
        <a href="{%  url 'core:home' %}"><h1>Home</h1></a>
        {% block content %}
        {% endblock content %}

        <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    </body>
</html>

users/templates/users/family/families.html
{% extends "core/base.html" %}


{% block content %}
<style>
     :root {
            --dark-grey: #2a2a2a;
            --light-grey: #3a3a3a;
            --orange: #ff6600;
            --light-orange: #ff8533;
        }
        .family-card {
            
            border: 1px solid var(--light-grey);
            transition: all 0.3s ease;
        }
        .family-card:hover {
            transform: translateY(-5px);
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .btn {
            transition: all 0.3s ease;
        }
        .btn:hover {
            transform: translateY(-2px);
        }
        
        
</style>


<header class="bg-gray-900 text-white p-4 mt-20">
    <div class="container mx-auto flex justify-between items-center">
        <h1 class="text-2xl font-bold text-orange-500">Familles RPV</h1>
        <!-- {% if eligible %}
    <a href="{% url 'users:new_family' %}"><button class="create-family-btn">Create a Family</button></a>
    {% else %}
    <button class="create-family-btn" disabled>Create a Family</button>
    {% endif %} -->
    <a href="{% url 'users:new_family' %}">
        <button onclick="createFamily()" class="btn btn-create px-4 py-2 rounded text-white">
            <i class="fas fa-plus mr-2"></i>Créer une famille
        </button>
    </a>
    </div>
</header>

<main class="flex-grow container text-white mx-auto px-4 py-8">
    <div id="families-container" class="grid grid-cols-1 md:grid-cols-2  gap-6">
        
        {% for family in families %}
        <div class="family-card bg-gray-700 rounded-lg p-6 shadow-md relative">
            <div class="flex items-center mb-4">
                <img src="{{family.family.profile_picture.url}}" alt="{{family.family}}" class="w-16 h-16 rounded-full mr-4 object-cover">
                <div>
                    <h2 class="text-xl font-semibold">{{family.family}}</h2>
                    <p class="text-sm text-gray-400">Rang: {{family.rank}}</p>
                </div>
            </div>
            <p class="mb-2"><i class="fas fa-user-tie mr-2"></i>Parrain: {{family.family.god_father}}</p>
            <p class="mb-4"><i class="fas fa-users mr-2"></i>Membres: {{family.n_members}}</p>
            <p class="mb-4"><i class="fas fa-key mr-2"></i>Points: {{family.family.points}}</p>

            <div class="flex space-x-2">
                <button onclick="joinFamily('{{family.family.id}}')" class="btn btn-join bg-orange-500 hover:bg-orange-600  px-4 py-2 rounded text-white flex-grow">
                    <i class="fas fa-sign-in-alt mr-2"></i>demande d'adhésion
                </button>
                <a href="{% url 'users:family_page' family.family.id %}">
                    <button  class="border-1 border-gray-800  px-4 py-2 rounded text-white flex-grow">
                    <i class="fas fa-eye mr-2"></i>Voir
                </button>
                </a>
                
            </div>


         </div>
        


        
        <!-- <li class="family-card">

            <img src="{{family.family.profile_picture.url}}" alt="Uzumaki Clan">
            <div class="family-card-content">
                <h3>{{family.family}}</h3>
                <p>God Father: {{family.family.god_father}}</p>
                <p>Member(s): {{family.n_members}}</p>
                <p>Points: {{family.family.points}}</p>
            </div>
            <div class="family-card-actions">
                
                {% if player.family or family.eligible_to_request  %}
                <button class="request-btn"  disabled>Request to Join</button>
                {% else %}
                <button class="request-btn" data-url=" {% url 'users:send_request' family.family.id  %}">Request to Join</button>
                {%endif%}
                <a href="{% url 'users:family_page' family.family.id %}">
                    <button class="view-btn">View Family</button>
                </a>
                
            </div>
        </li> -->
        {% endfor %}
       
        
    </div>

</main>

<script>
    
    function joinFamily(id) {
        console.log(`Joining family with id ${id}`);
        $.ajax({
                url: `/users/send_request/${id}`,
                type : "POST",
                data:{csrfmiddlewaretoken:"{{ csrf_token }}"},
                beforeSend: function(){
                    $('#loading-overlay').toggleClass('active')
                },
                success: function(res){
                    if(res.status == "success"){
                        console.log("request sent successfully")
                        showMyToast(res.message, 'success')
                        // e.target.disabled = true // jquery: $(e.target).prop("disabled",true)
                    }else{
                        showMyToast(res.message, 'info',4000)
                    }
                    
                },
                complete: function(){
                    $('#loading-overlay').toggleClass('active')
                },
                error: function(jqXHR, textstatus, errorThrown){
                    showMyToast('An error occured', 'error')
                }
            })
    }
    
</script>


{% endblock content %}



{% block not_content %}

  
<div class="container-family">
    
    
   
    {% if eligible %}
    <a href="{% url 'users:new_family' %}"><button class="create-family-btn">Create a Family</button></a>
    {% else %}
    <button class="create-family-btn" disabled>Create a Family</button>
    {% endif %}
    <div id="successAlertPlaceholder"></div>
    <ul class="family-list" id="familyList">
        {% for family in families %}
        <li class="family-card">
            <img src="{{family.family.profile_picture.url}}" alt="Uzumaki Clan">
            <div class="family-card-content">
                <h3>{{family.family}}</h3>
                <p>God Father: {{family.family.god_father}}</p>
                <p>Member(s): {{family.n_members}}</p>
                <p>Points: {{family.family.points}}</p>
            </div>
            <div class="family-card-actions">
                
                {% if player.family or family.eligible_to_request  %}
                <button class="request-btn"  disabled>Request to Join</button>
                {% else %}
                <button class="request-btn" data-url=" {% url 'users:send_request' family.family.id  %}">Request to Join</button>
                {%endif%}
                <a href="{% url 'users:family_page' family.family.id %}">
                    <button class="view-btn">View Family</button>
                </a>
                
            </div>
        </li>
        {% endfor %}
        
        <!-- More families can be added here -->
    </ul>
    
</div>

<script>
    function searchFamily() {
        const searchValue = document.getElementById('search').value.toLowerCase();
        const familyList = document.getElementById('familyList');
        const families = familyList.getElementsByTagName('li');

        for (let i = 0; i < families.length; i++) {
            const familyName = families[i].getElementsByClassName('family-card-content')[0].getElementsByTagName('h3')[0].innerText.toLowerCase();
            if (familyName.includes(searchValue)) {
                families[i].style.display = '';
            } else {
                families[i].style.display = 'none';
            }
        }
    }
</script>


<script>
    $(()=>{
        $(".request-btn").on("click",(e)=>{
            
            let url = e.target.dataset.url
            console.log(url)
            
            const alertPlaceholder = document.getElementById('successAlertPlaceholder')
            const appendAlert = (message, type) => {
            const wrapper = document.createElement('div')
            wrapper.innerHTML = [
                `<div class="alert alert-${type} alert-dismissible" role="alert">`,
                `   <div>${message}</div>`,
                '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
                '</div>'
            ].join('')

            alertPlaceholder.append(wrapper)
            }//appendAlert


            $.ajax({
                url: url,
                type : "POST",
                data:{csrfmiddlewaretoken:"{{ csrf_token }}"},
                success: function(res){
                    if(res.message == "success"){
                        console.log("request sent successfully")
                        appendAlert('Request to join family sent succesfully', 'success')
                        e.target.disabled = true // jquery: $(e.target).prop("disabled",true)
                    }else{
                        console.log("request not send")
                    }
                    
                }
            })
        })
        
    })

</script>


{% endblock not_content %}

users/templates/users/family/rankings.html
{% extends "core/base.html" %}
{% load static %}


{% block content %}
<style>
    :root {
        --dark-grey: rgb(31 41 55);
        --light-grey: rgb(67, 83, 105);
        --orange: #ff6600;
        --light-orange: #ff8533;
    }
    body {
        background-color: #1a1a1a;
        color: #e0e0e0;
        font-family: 'Arial', sans-serif;
    }
    .ranking-table {
        background-color: var(--dark-grey);
        border: 1px solid var(--light-grey);
    }
    .ranking-header {
        background-color: var(--light-grey);
    }
    .ranking-row:nth-child(even) {
        background-color: rgb(67, 83, 105,0.5);;
    }
    .ranking-row:hover {
        background-color: var(--light-grey);
    }
    .btn {
        transition: all 0.3s ease;
        background-color: var(--orange);
    }
    .btn:hover {
        background-color: var(--light-orange);
        transform: translateY(-2px);
    }
    .rank-1 {
        color: gold;
    }
    .rank-2 {
        color: silver;
    }
    .rank-3 {
        color: #cd7f32;
    }
</style>

<header class="bg-gray-900 text-orange-500 p-4 mt-20">
    <div class="container mx-auto">
        <h1 class="text-2xl font-bold">Classement de Familles - RPV</h1>
    </div>
</header>

<main class="flex-grow container mx-auto px-4 py-8">
    <div class="ranking-table rounded-lg overflow-hidden shadow-lg">
        <div class="ranking-header text-orange-500 p-4 font-bold text-lg grid grid-cols-5 gap-4">
            <div >Rang</div>
            <div class="col-span-2">Famille</div>
            <div>Membres</div>
            <div>Points</div>
        </div>
        <div id="rankings-container">
            <!-- Rankings will be dynamically inserted here -->
        </div>
    </div>
</main>


<script>
       

    function createRankingRow(family, rank) {
        const row = document.createElement('a');
        row.className = 'ranking-row p-4 grid grid-cols-5 gap-4 items-center';
        row.innerHTML = `
            <div class="font-bold ${rank <= 3 ? 'rank-' + rank : ''}">${rank}</div>
            <div class="col-span-2">${family.name}</div>
            <div>${family.members}</div>
            <div>${family.points.toLocaleString()}</div>
        `;
        row.setAttribute('href',`/users/family/${family.id}`)
        return row;
    }

    

    //renderRankings();
    $.ajax({
        url: '/users/families/rankings/data',
        type: 'GET',
        data: {csrfmiddlewaretoken:'{{csrf_token}}'},
        beforeSend: function(){
            
        },
        success: function(res){
            const families = res.families
            const container = document.getElementById('rankings-container');
            container.innerHTML = '';
        
        // Sort families by points in descending order
        // const sortedFamilies = families.sort((a, b) => b.points - a.points);
        
        families.forEach((family, index) => {
            container.appendChild(createRankingRow(family, index+1));
        });
        },
        complete: function(){
            
        },
        error: function(jqXHR, textstatus, errorThrown){
            showMyToast('An errror occured','error')
        }
    })

</script>

{% endblock content %}