blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.index,name='index'),
    path('<str:category>/posts',views.category, name='category'),
    path('posts/321<int:post_id>',views.blog_post, name='blog_post'),
]

core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('',views.index,name='index'),
    path('home',views.home,name='home'),
    path('search/<str:scope>',views.search_all,name = "search"),
    path('feed',views.get_posts,name='feed'),
    path('post/new',views.create_post, name='create_post'),
    path('post/delete/<int:id>',views.delete_post,name='delete_post'),
    path('post/modify/<int:id>',views.modify_post,name = 'modify_post'),
    path('post/<int:id>',views.post, name = 'post'),
    path('comment/<int:id>',views.comment, name = 'comment_action'),
    path('posts/<int:id>',views.post_page, name = 'post_page'),
    path('post/favorite/<int:id>',views.favorite, name = "favorite"),
    

    
    path('post/react/<int:post_id>',views.react_post,name="react"),
    path('post/comment/new/<int:post_id>',views.create_comment, name="comment"),
    path('comment/react/<int:comment_id>',views.react_comment,name="react_comment"),
    
    path('notifications', views.notifications, name='notifications'),
    path('notifications/all',views.get_notifications, name='all_notifications'),
    path('battle points',views.battle_points, name="battle_points"),

    path('rankings', views.rankings, name = 'rankings'),

]

para/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('adminxyz/', admin.site.urls),
    path('',include('core.urls',namespace='core')),
    path('users/',include('users.urls',namespace='users')),
    path('chats/',include('chat.urls',namespace='chats')),
    path('characters/',include('characters.urls',namespace='characters')),
    path('battles/',include('battles.urls',namespace='battles')),
    path('events/',include('events.urls',namespace='events')),
    path('blog/', include('blog.urls',namespace='blog')),
    path('moderator/', include('moderator.urls', namespace = 'moderator')),
    path('legal/', include('legal.urls', namespace = 'legal')),
    path('accounts/', include('allauth.urls')),
    path('',include('pwa.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models
from users.models import Player
from battles.models import Battle
import uuid
from django.utils import timezone

reaction_list = ["like","love","laugh","disapprove"]




class Post(models.Model):
    # id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    author = models.ForeignKey(Player, on_delete=models.CASCADE)
    body = models.TextField(blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(default=0)
    image = models.ImageField(upload_to='posts/',blank=True,null=True)
    

    def __str__(self):
        return f"{self.author}: {self.body[:20]}..."

class SavedPost(models.Model):
    player =  models.ForeignKey(Player, on_delete=models.CASCADE)    
    post = models.ForeignKey(Post,on_delete=models.CASCADE, null=True)
    date_added = models.DateTimeField()

    def __str__(self):
        return f"{self.player}: {self.post}"


class Comment(models.Model):
    # id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    author = models.ForeignKey(Player, on_delete=models.CASCADE)
    body = models.TextField()
    post = models.ForeignKey(Post,on_delete=models.CASCADE)
    #replies = models.ManyToManyField()
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to=f'posts/{author}/comments/',blank=True)
    likes = models.IntegerField(default=0)
    
    def __str__(self):
        return f"{self.author} in {self.post.body[:15]}"


#class CommenReply(models.Model):

class Reaction(models.Model):
    # id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    type = models.CharField(max_length=15, choices=[
        (i,i) for i in reaction_list
    ])
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.type} {self.player} in {self.post}" 


class CommentReaction(models.Model):
    # id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    type = models.CharField(max_length=15, choices=[
        (i,i) for i in reaction_list
    ])
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    

    def __str__(self):
        return f"{self.type} {self.player} in {self.comment}"     


notification_types=["commented_post",""]
class Notification(models.Model):
    target = models.ForeignKey(Player, on_delete=models.CASCADE)
    content = models.TextField()
    url = models.CharField(max_length=100)
    date_sent = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    
    def __str__(self):
        return f"{self.target}: {self.content[:10]}..."
    

class Feed(models.Model):
    player = models.ForeignKey(Player, on_delete = models.CASCADE)
    posts = models.ManyToManyField(Post,  through='PostFeed')
    battles = models.ManyToManyField(Battle, through='BattleFeed')

    def __str__(self):
        return f"{self.player}"

class PostFeed(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('post','feed')  


class BattleFeed(models.Model):
    battle = models.ForeignKey(Battle, on_delete=models.CASCADE)
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('battle','feed')            

core/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.db.models import Q,QuerySet
from django.db.models import Case, When,F
from django.urls import reverse
from django.contrib.auth.models import User,auth
from django.http import JsonResponse,HttpResponseRedirect
from users.models import Player,PlayerNotification,Family
from django.contrib.auth.decorators import login_required
from .models import *
from events.models import Tournament
from battles.models import Battle,Challenge
from chat.models import FamilyMessage
import battles.views as battle_views
import users.views as users_views
from pathlib import Path
from django.core.serializers import serialize
from django.forms.models import model_to_dict
import os
import json
from django.views.decorators.csrf import csrf_exempt
import datetime
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from django.utils.translation import gettext as _
from users.users_utility import get_player
from utility import _time_since,_parse_number,decrypt_message,sendWelcomeEmail,generate_referall_code
import random
from django.contrib.gis.geoip2 import GeoIP2
import re


BASE_DIR = Path(__file__).resolve().parent.parent

def get_characters():
    characters_file = os.path.join(BASE_DIR,"characters/playable_characters.json")
    with open(characters_file,"r") as f:
        characters = json.load(f)
    return characters      


def remove_points(player:Player,points):
    battle_points = player.battle_points
    new_battle_points = battle_points - points
    
    if new_battle_points <=0:
        new_battle_points = 0

    player.battle_points = new_battle_points    
    player.save()

def add_points(player:Player, points:int):
    player.battle_points += points
    player.save()
    



def index(request):
    player = get_player(request.user)
    if player:
        return redirect('/home')
    else:
        return render(request,"core/index.html")

def get_comments(post):
    comments = Comment.objects.filter(post = post)
    return comments

def _get_comment(player:Player,comment:Comment):
    return  {   
            'id': comment.id,
            'author': {
                'player': str(comment.author),
                'username': comment.author.user.username,
                'profile_picture': comment.author.profile_picture.url,
            },
            'comments': len(Comment.objects.filter(post = comment.post)),
            'liked': _liked_comment(player, comment),
            'likes': _parse_number(len(CommentReaction.objects.filter(comment = comment))),
            'body': comment.body,
            'timestamp': _time_since(comment.date_added)  

        } 

def get_comments_dict(player:Player,post:Post):
    comments = Comment.objects.filter(post = post).order_by('-date_added')
    comments_dict = []

    data = [
        {   
            'id': comment.id,
            'author': {
                'id': comment.author.id ,
                'player': str(comment.author),
                'username': comment.author.user.username,
                'profile_picture': comment.author.profile_picture.url,
            },
            'liked': _liked_comment(player, comment),
            'likes': _parse_number(len(CommentReaction.objects.filter(comment = comment))),
            'body': comment.body,
            'timestamp': _time_since(comment.date_added)  

        } for comment in comments
    ]

    for comment in comments:
        comment_dict = model_to_dict(comment)

        if comment_dict['image']:
            comment_dict['image'] = comment.image.url
        else:
            comment_dict['image'] = None

        comments_dict.append(comment_dict)
    

    return data

def get_time_posted(post):
    date_posted = post.date_added
    current_time = datetime.datetime.hour

def get_notifs(player):
    player_notifs = PlayerNotification.objects.filter(target= player, read = False)
    notifs = Notification.objects.filter(target = player, read = False)
    challenges = Challenge.objects.filter(target = player)
    n_notifs = len(player_notifs) + len(notifs) + len(challenges)

    if n_notifs == 0:
        return ""
    if n_notifs>9:
        return "9+"
    else:
        return f"{n_notifs}"
        
@login_required
def home(request):


    posts = Post.objects.all()
    battles = Battle.objects.filter(status = "finished")
    

    characters = get_characters()    

    posts = list(posts)
    battles = list(battles)
    #get the feed
    posts_data = [ {
            "type": "post",
            "post": post,
            "comments": get_comments(post),
            "n_comments": len(get_comments(post)),
            "time_posted": _time_since(post.date_added),
        } for post in posts
        ]
    battles_data = [
        {
        "type": "battle",
        "battle": battle
    } for battle in battles
    ]

    feed = posts_data + battles_data
    

    #sort the list of characters
    sorted_characters = sorted(characters["playable_characters"], key = lambda item: item["name"]) 

    # player = get_object_or_404(Player, user = request.user )
    player = get_player(request.user)
    if not player:
        return redirect('/users/signin')
    
    

    feed,created = Feed.objects.get_or_create(player = player)
    
    feed.posts.clear()
    feed.battles.clear()
    
    feed.save()
    players = Player.objects.exclude( user = request.user)
    player_notifs = PlayerNotification.objects.filter(target= player, read = False)
    n_notifs = len(player_notifs)
    can_invite = False

    fl_message_data = None

    #check if player is in a family 
    if player.family:
        player_family = player.family 
        #check if player is the head of a family to determine if he  can send invites to other players
        if player == player_family.god_father :
            can_invite = True

        family_last_message = FamilyMessage.objects.filter(family = player_family).order_by('-date_sent').first()
        
        if family_last_message:
            content =  decrypt_message(family_last_message.content)[:7]+'...'
            if family_last_message.image:
                content = f'a envoyé une image'
            fl_message_data = {
                "sender":family_last_message.sender.user.username,
                'content': content,
            }
        else:
            fl_message_data = {
                "sender":"sender",
                'content': "Le dernier messaage seras affiché ici",
            }          
    now = datetime.datetime.now()          
    
    challenges = Challenge.objects.filter(target = player).order_by('-date_sent')[:2]
    

    families  = Family.objects.all()
    top_families = sorted(families, key = lambda family : family.points ,reverse=True)[:2]
    events = Tournament.objects.all().order_by('-date_created')[:2]
    to_translate = _("Chats")

    context = {
        
        "posts":posts,
        "players":players,
        'playerName': str(player),
        "player_notifs":player_notifs,
        "player":player,
        "can_invite":can_invite,
        "characters": sorted_characters ,
        "feed":feed,
        "n_notifs":get_notifs(player),
        'fl_message':fl_message_data,
        'top_families': top_families,
        'top_players': users_views._monthly_players_ranking()[:3],
        'battle_cover': random.randint(1,1),
        'events': events,
        "to_translate": to_translate,
        'challenges': challenges
        
        }
    
    
    return render(request,"core/home.html",context)

def _liked_comment(player:Player, comment:Comment):
    liked = False
    reactions = CommentReaction.objects.filter(comment = comment, player = player)
    if reactions.exists():
        liked = True
    return liked 

def _liked_post(player:Player, post:Post):
    liked = False
    reactions = Reaction.objects.filter(post = post, player = player)
    if reactions.exists():
        liked = True
    return liked    

    

def _posts_data(player:Player,posts):
    return [
         {
           "feed_item": "post",
            "id": post.id,
            "author":{  
                        'id':post.author.id,
                        "name":post.author.user.username,
                        'player': str(post.author),
                        'profile_picture':post.author.profile_picture.url
                        },
            'body':post.body,
            'liked': _liked_post(player, post),
            'likes':_parse_number(post.likes, True),
            'image':post.image.url if post.image else None,
            "comments": get_comments_dict(player,post),
            "n_comments": _parse_number(len(get_comments(post)), True),
            "time_posted": _time_since(post.date_added),
            'is_favorite': SavedPost.objects.filter(player = player, post = post).exists(),
        } for post in posts
    ]

def _post_data(player:Player, post:Post):
    return {
            "feed_item": "post",
            "id": post.id,
            "author":{  
                        'id':post.author.id,
                        "name":post.author.user.username,
                        'player': str(post.author),
                        'profile_picture':post.author.profile_picture.url
                        },
            'body':post.body,
            'liked': _liked_post(player, post),
            'likes':_parse_number(post.likes,True),
            'is_favorite': SavedPost.objects.filter(player = player, post = post).exists(),
            'image':post.image.url if post.image else None,
            "comments": get_comments_dict(player,post),
            "n_comments": _parse_number(len(get_comments(post)),True),
            "time_posted": _time_since(post.date_added),
        }

def get_posts(request):
    player = Player.objects.get(user = request.user)
    feed = Feed.objects.get(player = player)
    #posts criterias:
    #1. family members posts
    #2. Recent posts
    feed_data = []

core/templates/feed/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>Feed</title>
        <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    </head>
<body>
    <a href="{% url 'core:home' %}">Home</a><br>
    {% block content %}
    {% endblock content %}

</body>
</html>    

core/templates/feed/index.html
{% extends "core/base.html" %}
{% load static %}
<!--<img src="{{post.image.url}}" width="100px" height="100px">
-->
{% block content %}
<style>
.post-box{
    position: absolute;
    z-index: 3;
    margin: auto;
    width: 50%;
    border: 1px solid black;
    background-color: bisque;
    display: none;
}
</style>
<style>
    
    .post-card {
        /*width: 400px;*/
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        margin: 20px;
        overflow: hidden;
    }
    .post-card .post-header {
        display: flex;
        align-items: center;
        padding: 15px;
        border-bottom: 1px solid #ddd;
    }
    .post-card .post-header img {
        height: 40px;
        width: 40px;
        border-radius: 50%;
        margin-right: 10px;
    }
    .post-card .post-header .post-info {
        flex: 1;
    }
    .post-card .post-header .post-info .user-name {
        font-weight: bold;
    }
    .post-card .post-header .post-info .post-time {
        font-size: 12px;
        color: #888;
    }
    .post-card .post-header .post-options {
        cursor: pointer;
    }
    .post-card .post-content {
        padding: 15px;
    }
    .post-card .post-content .post-text {
        margin-bottom: 10px;
    }
    .post-card .post-content .post-image {
        width: 100%;
        border-radius: 8px;
    }
    .post-card .post-actions {
        display: flex;
        justify-content: space-between;
        padding: 10px 15px;
        border-top: 1px solid #ddd;
    }
    .post-card .post-actions button {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 15px;
        border-radius: 8px;
        cursor: pointer;
    }
    .post-card .post-actions button:hover {
        background-color: #0056b3;
    }
    .post-card .comment-section {
        display: flex;
        padding: 10px 15px;
        border-top: 1px solid #ddd;
    }
    .post-card .comment-section input[type="text"] {
        flex: 1;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 8px;
        margin-right: 10px;
    }
    .post-card .comment-section button {
        background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 15px;
        border-radius: 8px;
        cursor: pointer;
    }
    .post-card .comment-section button:hover {
        background-color: #0056b3;
    }
</style>


<!-- popup style -->
<style>
     
    .popup {
      display: none;
      position: fixed;
      top: 50%;
      left: 50%;
      width: 80%;
      transform: translate(-50%, -50%);
      background-color: white;
      padding: 20px;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
      z-index: 1000;
    }

    .close-button {
      position: absolute;
      top: 10px;
      right: 10px;
      background-color: #007bff;
        color: white;
        border: none;
        padding: 10px 15px;
        border-radius: 8px;
        cursor: pointer;
    }
  
</style>
<!--
<button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">
    Click to toggle popover</button>
-->



    
  <div id="comments" class="comments-area popup">
    <button id="close-btn" class="close-button"><i class="fa fa-times"></i></button>
  </div>


{% for post in posts  %}
<div class="post-card">
    <div class="post-header">
        <img src="{{post.author.profile_picture.url}}" alt="Profile Picture">
        <div class="post-info">
            <div class="user-name">{{post.author}}</div>
            <div class="post-time">2 hours ago</div>
        </div>
        <div class="post-options">
            <i class="fa fa-ellipsis-h"></i>
        </div>
    </div>
    <div class="post-content">
        <div class="post-text">{{post.body}}</div>
        {% if post.image %}
        <img src="{{post.image.url}}" width="100%" height="100%" alt="Post Image" class="post-image">
        {% endif %}
    </div>
    <div class="post-actions">
        <button class="like-btn" data-post_id="{{post.id}}" data-link="{% url 'core:react' post.id %}">
            {% if post.reacted %}
            <i id="like-icon" class="fa fa-thumbs-up"></i>
            {% else %}
            <i id="like-icon" class="fa fa-thumbs-o-up"></i>
            {% endif %}
            <span id="post-likes-{{post.id}}">{{post.likes}}</span></button>
        <button class="comment-btn" data-link="{% url 'core:post' post.id %}" data-post_id="{{post.id}}"><i class="fa fa-comment"></i></button>
    </div>
    <div class="comment-section">
        <input id="input-comment-{{post.id}}"  type="text" placeholder="Write a comment...">
        <button class="send-comment" data-post_id="{{post.id}}"  data-link="{% url 'core:comment' post.id %}"><i class="fa fa-paper-plane"></i></button>
    </div>
</div>
{% endfor %}

<a href="{% url 'core:create_post' %}">Create a post</a>

<!--
{% for post in posts  %}
<div class="post-box">
    <!--
    <div class="main">
        <p class="body"></p>
    </div>
    <div id="comments">

    </div>

<div id="comments">

</div>
<textarea id="input-comment" name="comment" cols="30" rows="2" placeholder="write your comment"></textarea>
<button id="send-comment" data-link="{% url 'core:comment' post.id %}">Send</button>
</div>

<h3>{{post.author}}</h3>
<p>{{post.body}}</p>
{% if post.image %}
<img src="{{post.image.url}}" width="100px" height="100px">
{% endif %}
<span id="post-likes-{{post.id}}">{{post.likes}}</span><button class="like-btn" data-post_id="{{post.id}}" data-link="{% url 'core:react' post.id %}">Like</button>
<span>
    <button class="comment-btn" data-link="{% url 'core:post' post.id %}" data-post_id="{{post.id}}">Comment</button></span>
{% if post.author.user == request.user %}
<form action="{% url 'core:delete_post' post.id %}" method="post">
    {% csrf_token %}
    <button type="submit">DELETE</button>
</form>

<a href="{% url 'core:modify_post' post.id %}">Edit</a>
{% endif %}
-->
{% endfor %}


<script>
     

    $(()=>{
        const popup = document.getElementById('comments');
    const closeButton = document.querySelector('#close-btn');
    $(".close-button").on('click', (e) => {
            
            popup.style.display = 'none';
            $("#comments").empty()
            });
    
        $(".like-btn").on("click",(e)=>{
           
            const post_id = String(e.target.dataset.post_id)
            $.ajax({
                url: e.target.dataset.link,
                type: "POST",
                data: { csrfmiddlewaretoken:"{{ csrf_token }}" },
                beforeSend: function(){
                    $(e.target).hide()
                    //show loader
                },
                success: function(res){
                    if(res.status == 'success'){
                        let likes_span = $(`#post-likes-${post_id}`)
                        let likes = parseInt(likes_span.text())
                        let like_icon = $(e.target).children().eq(0)
                        if(res.message == 'liked'){
                            like_icon.removeClass("fa fa-thumbs-o-up")
                            like_icon.addClass("fa fa-thumbs-up")

                            likes_span.text(likes+1)
                            
                        }else{
                            like_icon.removeClass("fa fa-thumbs-up")
                            like_icon.addClass("fa fa-thumbs-o-up")
                            likes_span.text(likes-1)
                            
                        }
                        

                    }

                },
                complete: function(){
                    $(e.target).show()
                    //remove loader
                }

            })
        })

        $(".comment-btn").on("click",(e)=>{
            popup.style.display = 'block';

            let url = e.target.dataset.link
            $.ajax({
                url:url,
                type:"GET",
                beforeSend: function(){
                    console.log("wait..")
                },
                success:function(res){
                    if(res.status == "success"){
                        console.log(res.post.comments)
                        $("#comments").append(
                        `<button id="close-btn" class="close-button"><i class="fa fa-times"></i></button>`
                        )
                        res.post.comments.forEach(comment => {
                            $("#comments").append(`
                            <div class="comment">
                                <b>${comment.author}</b>
                                <p>${comment.body}</p>
                            </div>    
                            `)
                            $(".close-button").on('click', (e) => {
                                popup.style.display = 'none';
                                $("#comments").empty()
                            });
    
                            
                        });
                            
                    }
                }
            })
        })

        $(".send-comment").on("click",(e)=>{
            console.log("clicked")
            let post_id = e.target.dataset.post_id

            $.ajax({
                url: e.target.dataset.link,
                type:"POST",
                data:{csrfmiddlewaretoken:"{{csrf_token}}","comment":$(`#input-comment-${post_id}`).val()},
                success: function(res){
                    console.log(res)
                }

            })
        })
        
    })
</script>

{% endblock content %}

core/templates/feed/modify_post.html
{% extends "core/base.html" %}

{% block content %}
<style>
.container-post{
    width: 50%;
    margin: 1rem auto;

    form{
        display: flex;
        gap: 10px;
        flex-direction: column;
    }
}
</style>

<div class="container-post">
    <form action="{% url 'core:modify_post' post.id %}" method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <textarea name="body">{{post.body}}</textarea>

    <input type="file" name="new_image" value="{{post.image}}">
    <button type="submit" class="btn btn-secondary">Save</button>

</form>

</div>


{% endblock content %}

core/templates/feed/new_post.html
{% extends "feed/base.html" %}
{% block content %}

<div>
    <form method="post" action="{% url 'core:create_post' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <textarea name="body"></textarea>
        <input type="file" name = "image">
        <button type="submit">Publish</button>

    </form>
</div>


{% endblock content %}